---
- name: 1. install Apache
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - apache2

- name: 2. install PHP and modules
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-cli
    - php7.0-common
    - php7.0-mbstring
    - php7.0-gd
    - php7.0-intl
    - php7.0-xml
    - php7.0-mysql
    - php7.0-mcrypt
    - php7.0-zip
#  notify:
#    - restart apache2


- name: 3. start Apache
  service: name=apache2 state=running enabled=yes

- name: 4. install Hello World PHP script
  copy: src=hello.php dest=/var/www/html/hello.php mode=0664
  
- name: 5. install index html
  copy: src=index.html dest=/var/www/html/index.html mode=0664
  
