---
- hosts: "tag_tool_ansible"
  connection: "local"
  gather_facts: false
  vars:
    region: "eu-central-1"
    id: "FC_FRONT_0001"

  tasks:
  - name: "Remove tagged EC2 instances from security group"
    ec2:
      state: "running"
      id: "{{id}}"
      region: "{{ region }}"
      instance_ids: "{{ ec2_id }}"
      group_id: ""
    delegate_to: "localhost"
      
  - name: "Terminate tagged EC2 instances"
    ec2:
      state: "absent"
      region: "{{ region }}"
      instance_ids: "{{ ec2_id }}"
      wait: true
    delegate_to: "localhost"

- hosts: "localhost"
  connection: "local"
  gather_facts: false
  vars:
    region: "eu-central-1"

  tasks:
  - name: "Remove security group"
    ec2_group:
      name: "sg_front"
      description: "security groups"
      region: "{{ region }}"
      state: "absent"
